### ISSUE TITLE
Feature request: support for compound emojis

### ISSUE THREAD

**Issue by fluffynuts** [Drarig29/is-emoji#1]
Hi, thanks for `auto-paste-emoji` and this tool - I can (mostly) use emojis without hassle, though I've made some considerable changes to `auto-paste-emoji` - I should open a PR to see if you're interested - changes are to make it more reliable on my machine, so I'm not sure if that's globally-applicable... but back to the topic:

I notice that I can use `auto-paste-emoji` to paste "simpler" emoji like 🔥 or ❤, but some emoji are compound, and `is-emoji` doesn't seem to pick that up. Case in point: ❤‍🔥, which doesn't even paste in here nicely, but should be an heart on fire. Or 🧑🏻‍🚒, which pastes to a terminal as a combination of 4 characters:

![image](https://user-images.githubusercontent.com/4669340/227452360-85c9422e-cc76-4af6-87d2-51ce2b37f404.png)

but pastes properly where it's supported - like previously in this issue 😂

**Comment by Drarig29** [comment]
Hi! Thanks for the feature request!
And yes, I would be interested to see your changes to `auto-paste-emoji` 👍 

Back to the topic: that was an interesting issue and I learnt a lot about emojis!
I added unit tests and edited the regex. Now it should support compound emojis too :grin:

You can find the new version here: [v0.1.1](https://github.com/Drarig29/is-emoji/releases/tag/v0.1.1)

**Comment by fluffynuts** [comment]
🧑🏻‍🚒! tested working with the latest `is-emoji` :D
